### ISSUE TITLE
Incorrect quick filter attribute text

### ISSUE THREAD

**Issue by calebhalvy** [ag-grid/ag-grid-docs#166]
ag-grid-docs/src/javascript-grid-filter-quick/index.php contains a sentence,
`If you are using a framework such as Angular or React, you can set bind the quick filter text to the
    <code>quickFilter</code> attribute.`
Shouldn't this be quickFilterText?

**Comment by stoyandamov** [comment]
This is still not fixed at https://www.ag-grid.com/javascript-grid-filter-quick/#gsc.tab=0 after half an year

**Comment by ChrisBirkett** [comment]
https://github.com/ag-grid/ag-grid-docs/pull/175

**Comment by StephenCooper** [comment]
Thanks for this, we did not see them as this repo is no longer maintained and the AG Grid Documentation now lives in our mono repo under [documentation](https://github.com/ag-grid/ag-grid/tree/latest/grid-packages/ag-grid-docs/documentation). The docs are correct now.
