### ISSUE TITLE
Should IEnterpriseGetRowsParams definition include startRow and endRow?

### ISSUE THREAD

**Issue by ZackWard** [ag-grid/ag-grid-docs#167]
The documentation for the [Enterprise Row Model](https://www.ag-grid.com/javascript-grid-enterprise-model/?framework=react#gsc.tab=0) currently uses this definition for `IEnterpriseGetRowsParams`.

```javascript
interface IEnterpriseGetRowsRequest {

    // details for the request
    rowGroupCols: ColumnVO[];

    // columns that have aggregations on them
    valueCols: ColumnVO[];

    // what groups the user is viewing
    groupKeys: string[];

    // if filtering, what the filter model is
    filterModel: any;

    // if sorting, what the sort model is
    sortModel: any;
}

// we pass a VO (Value Object) of the column and not the column itself,
// so the data can be converted to a JSON string and passed to server side
export interface ColumnVO {
    id: string;
    displayName: string;
    field: string;
    aggFunc: string;
}
```

However, the example mockServerSimple uses the startRow and endRow properties of the request [here](https://github.com/ag-grid/ag-grid-docs/blob/39cc761e572d736d56d1290fa6e060111fbdc776/src/javascript-grid-enterprise-model/mockServerSimple.js#L124). These properties are documented on the [Infinite Scrolling Row Model](https://www.ag-grid.com/javascript-grid-infinite-scrolling/#gsc.tab=0), but not here. 

Am I misunderstanding the `IEnterpriseGetRowsParams` interface, or should it actually be documented as follows?

```javascript
interface IEnterpriseGetRowsRequest {

    // The first row index to get.
    startRow: number;

    // The first row index to NOT get.
    endRow: number;

    // details for the request
    rowGroupCols: ColumnVO[];

    // columns that have aggregations on them
    valueCols: ColumnVO[];

    // what groups the user is viewing
    groupKeys: string[];

    // if filtering, what the filter model is
    filterModel: any;

    // if sorting, what the sort model is
    sortModel: any;
}

// we pass a VO (Value Object) of the column and not the column itself,
// so the data can be converted to a JSON string and passed to server side
export interface ColumnVO {
    id: string;
    displayName: string;
    field: string;
    aggFunc: string;
}
```

If so, I would be happy to submit a PR for this.

**Comment by StephenCooper** [comment]
The interfaces are now generated from the code source so that this mismatch will not happen going forward.
