### ISSUE TITLE
Incorrect name of callback in the Change Log for v13.2.0

### ISSUE THREAD

**Issue by nupurgrover** [ag-grid/ag-grid-docs#170]
The name of callback `suppressKeyboardEvent` in the [changelog](https://www.ag-grid.com/change-log/changeLogIndex.php#gsc.tab=0) for v13.2.0 is incorrectly written as `suppressKeyboardNavigation`. This makes it difficult to find out which version was the callback introduced in (I just wasted a couple of hours)

**Comment by nupurgrover** [comment]
@seanlandsman Are you accepting PRs? I am happy to provide one for this

**Comment by seanlandsman** [comment]
Hi @nupurgrover yes, that would be great! thanks

**Comment by nupurgrover** [comment]
@seanlandsman Here you go https://github.com/ag-grid/ag-grid-docs/pull/173

**Comment by seanlandsman** [comment]
thanks
