### ISSUE TITLE
Link for `source code of themes` points to 404 github link

### ISSUE THREAD

**Issue by Prithvirajbilla** [ag-grid/ag-grid-docs#184]
https://www.ag-grid.com/javascript-grid-styling/#customizing-sass-variables

At the bottom of the page, there is a github link to source code of the themes.  But that link results in 404.

**Comment by StephenCooper** [comment]
Thanks for this, we did not see them as this repo is no longer maintained and the AG Grid Documentation now lives in our mono repo under [documentation](https://github.com/ag-grid/ag-grid/tree/latest/grid-packages/ag-grid-docs/documentation).
