### ISSUE TITLE
Row Grouping page shows up as an enterprise feature in the left side menu, but not in the header for the page

### ISSUE THREAD

**Issue by sjetha-pason** [ag-grid/ag-grid-docs#190]
If you navigate to the [Row Grouping page](https://www.ag-grid.com/javascript-grid-grouping/) you will see that the header doesn't contain the "e" that shows that this is an enterprise feature, yet the page listed on the left side page list shows the "e".

It is unclear if this is an enterprise feature or not.

**Comment by StephenCooper** [comment]
Thanks for this, we did not see them as this repo is no longer maintained and the AG Grid Documentation now lives in our mono repo under [documentation](https://github.com/ag-grid/ag-grid/tree/latest/grid-packages/ag-grid-docs/documentation).

This has been fixed.
