### ISSUE TITLE
suppressKeyboardEvent() isn't called if isPopup() returns true

### ISSUE THREAD

**Issue by AsterisDigitalLab** [ag-grid/ag-grid-docs#195]
I tried creating a custom cell renderer that has isPopup() that returns true. And I put suppressKeyboardEvent in colDef but suppressKeyboardEvent function is never called. If the isPopup() returns false, suppressKeyboardEvent is called successfully.

**Comment by StephenCooper** [comment]
Thanks for this, we did not see them as this repo is no longer maintained and the AG Grid Documentation now lives in our mono repo under [documentation](https://github.com/ag-grid/ag-grid/tree/latest/grid-packages/ag-grid-docs/documentation).
