### ISSUE TITLE
Typo: FirstDataRendereredEvent

### ISSUE THREAD

**Issue by philtyl** [ag-grid/ag-grid-docs#202]
FirstDataRendereredEvent => FirstDataRenderedEvent

https://www.ag-grid.com/javascript-grid-events/

**Comment by StephenCooper** [comment]
Thanks for this PR, we did not see it as this repo is no longer maintained and the AG Grid Documentation now lives in our mono repo under [documentation](https://github.com/ag-grid/ag-grid/tree/latest/grid-packages/ag-grid-docs/documentation).

I see this has already been corrected now.
